name: Publish

on:
  push:
    branches:
      - v2.0.x

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Publish
      uses: Apehum/mc-publish@v1.0
      with:
        # You don't need this section if you don't want to publish
        # your assets to Modrinth
        # modrinth-id: AANobbMI
        # modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

        # You don't need this section if you don't want to publish
        # your assets to CurseForge
        # curseforge-id: 394468
        # curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

        # You don't need this section if you don't want to publish
        # your assets to GitHub
        split-releases: true
        files-primary: build/libs/*-@(forge|fabric)-*.jar
        github-token: ${{ secrets.GITHUB_TOKEN }}
        github-generate-changelog: false
        github-prerelease: true
